### ISSUE TITLE
Move to using libjail-rs

### ISSUE THREAD

**Issue by phyber** [phyber/jail_exporter#11]
After becoming comfortable with the C FFI, it's probably time to move to using libjail-rs for the `jail_get` calls.

**Comment by fabianfreyer** [comment]
Hi! I'm the author of libjail-rs. Just a heads up - while I can't really think of things that will still change in a breaking way, I'm not ready for making any API stability guarantees yet. However, if you do end up using it, please let me know how this goes and what features you'd be missing :).

FWIW iteration over running jails [should be landing soon](https://github.com/fubarnetes/libjail-rs/pull/6) in 0.0.4 - I guess this is the main feature you would be using?

**Comment by fabianfreyer** [comment]
Thanks! Having a jail prometheus exporter seems to be very useful too!

After merging #13, how'd you feel about upstreaming some of the `rctl` information into `libjail-rs`? I've opened https://github.com/fubarnetes/libjail-rs/issues/8 for this.

**Comment by phyber** [comment]
I'm open to adding the `rctl` usage stuff to `libjail-rs`, yeah. Licensing isn't an issue and I'm happy to contribute it under the 3-Clause BSD license.
