### ISSUE TITLE
Release on crates.io

### ISSUE THREAD

**Issue by fabianfreyer** [phyber/jail_exporter#32]
Any chance we can have this released on [crates.io]? This would enable installing this with a `cargo install jail_exporter`.

[crates.io]: https://crates.io/

**Comment by phyber** [comment]
👍 
I'll take a look at doing this shortly.

**Comment by phyber** [comment]
There will probably be a 0.9.9 before this happens, I'm tweaking the `Cargo.toml` to make `cargo package` happier and exclude various files that wouldn't be needed for a `cargo install`. It will probably contain everything other than the documentation link.

**Comment by phyber** [comment]
This crate is now published on crates.io at https://crates.io/crates/jail_exporter
