### ISSUE TITLE
Create FreeBSD port.

### ISSUE THREAD

**Issue by phyber** [phyber/jail_exporter#6]
Since this exporter is for FreeBSD jails, a FreeBSD port would be nice.

**Comment by phyber** [comment]
Basic rc.d script has been added to the repo.

**Comment by phyber** [comment]
I have a port locally, which should be submitted shortly. I had been holding back for a few changes to how the exporter is passed to the HTTPd state, but that will take a while given #27.

**Comment by phyber** [comment]
Local port updated with these changes, just got to wait a while for Rust to build and stuff for the `poudriere testport`.

**Comment by phyber** [comment]
Port has been submitted, awaiting review and commit.

**Comment by phyber** [comment]
This has still not been committed. I have prepared an updated version of the port, since a release has been made in the meantime. Once tested locally, the diff in the bug tracker will be updated.

**Comment by tykling** [comment]
what is the status of the port?

**Comment by phyber** [comment]
The port has been sat on the bug tracker for a while waiting for a ports maintainer to merge it. I should poke some people on IRC/Discord.

**Comment by phyber** [comment]
The port has finally been merged! https://www.freshports.org/sysutils/jail_exporter/
